In [1]:
import numpy as np


## numpy array

In [3]:
benimListem=[20,30,40]

In [4]:
benimListem

[20, 30, 40]

In [6]:
type(np.array(benimListem))

numpy.ndarray

In [8]:
matrixListesi=[[10,20,30],[20,30,40],[30,40,50]]

In [9]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [11]:
list(range(1,13))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [12]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
np.arange(1,17,3)

array([ 1,  4,  7, 10, 13, 16])

## zeros

In [14]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## ones


In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace

In [21]:
np.linspace(0,365,27)

array([  0.        ,  14.03846154,  28.07692308,  42.11538462,
        56.15384615,  70.19230769,  84.23076923,  98.26923077,
       112.30769231, 126.34615385, 140.38461538, 154.42307692,
       168.46153846, 182.5       , 196.53846154, 210.57692308,
       224.61538462, 238.65384615, 252.69230769, 266.73076923,
       280.76923077, 294.80769231, 308.84615385, 322.88461538,
       336.92307692, 350.96153846, 365.        ])

## eye

In [22]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

## random

In [24]:
np.random.randn(5)

array([-9.04597146e-01, -2.01172266e-01, -1.35405346e+00, -3.38358571e-01,
        1.01053491e-03])

In [29]:
np.random.randint(90,100)

92

In [30]:
np.random.randint(1,100,7)

array([ 3, 17,  3,  7, 67, 15, 89])

In [31]:
benimDizim=np.arange(30)

In [32]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
benimDizim=np.random.randint(1,100,15)

In [37]:
benimDizim

array([25, 41, 36, 75, 34, 50, 94, 46,  9,  7, 13, 10, 13, 38, 39])

## numpy dizi methodları

In [42]:
benimDizim.reshape(3,5)

array([[25, 41, 36, 75, 34],
       [50, 94, 46,  9,  7],
       [13, 10, 13, 38, 39]])

In [43]:
benimDizim.max()

94

In [44]:
benimDizim.min()

7

In [45]:
benimDizim.argmax()

6

In [46]:
benimDizim.argmin()

9