In [1]:
import numpy as np

In [3]:
benimDizim=np.arange(15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[2:9]=-1

In [6]:
benimDizim

array([ 0,  1, -1, -1, -1, -1, -1, -1, -1,  9, 10, 11, 12, 13, 14])

In [7]:
baskaDizi=np.arange(15)

In [8]:
slicingDizisi=baskaDizi[4:8]

In [9]:
slicingDizisi[:]=18

In [10]:
baskaDizi[4:8]

array([18, 18, 18, 18])

In [11]:
baskaDizi

array([ 0,  1,  2,  3, 18, 18, 18, 18,  8,  9, 10, 11, 12, 13, 14])

## matrix

In [12]:
benimListem=[[5,7,9],[13,15,17],[7,24,25]]

In [13]:
benimMatrixDizim=np.array(benimListem)

In [14]:
benimMatrixDizim


array([[ 5,  7,  9],
       [13, 15, 17],
       [ 7, 24, 25]])

In [15]:
benimMatrixDizim[1][2]

17

In [16]:
benimMatrixDizim[1,2]

17

In [24]:
benimMatrixDizim[1:,1]

array([15, 24])

## operasyonlar

In [25]:
yeniBirDizi=np.random.randint(1,100,17)

In [27]:
yeniBirDizi

array([15, 91, 15, 97,  9,  2, 42, 75, 15, 78, 23, 57, 75, 30, 17, 55, 31])

In [28]:
yeniBirDizi<50

array([ True, False,  True, False,  True,  True,  True, False,  True,
       False,  True, False, False,  True,  True, False,  True])

In [29]:
sonuc=yeniBirDizi<50

In [30]:
sonuc

array([ True, False,  True, False,  True,  True,  True, False,  True,
       False,  True, False, False,  True,  True, False,  True])

In [31]:
yeniBirDizi[sonuc]

array([15, 15,  9,  2, 42, 15, 23, 30, 17, 31])

In [32]:
sonDizi=np.arange(24)

In [33]:
sonDizi


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
sonDizi+=sonDizi


In [35]:
sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [36]:
np.sqrt(sonDizi)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262,
       5.47722558, 5.65685425, 5.83095189, 6.        , 6.164414  ,
       6.32455532, 6.4807407 , 6.63324958, 6.78232998])

In [37]:
np.max(sonDizi)

46

In [39]:
np.min(sonDizi)

0